/**
 * @generated by docs/maps/scripts/architecture-sync.mjs — do not edit.
 *
 * Measured from the tree, so the map's numbers cannot drift from the code.
 * `UNCLAIMED` is what no module on the map covers: run the sync script, then
 * either give an existing module a wider pattern in coverage.json or add the
 * node the repo has been missing.
 */

export const MEASURED: Record<string, { count: number; loc: number }> = {
  'audio': { count: 7, loc: 873 },
  'auth': { count: 4, loc: 306 },
  'boot': { count: 1, loc: 45 },
  'camera': { count: 10, loc: 1989 },
  'config': { count: 3, loc: 84 },
  'device-controls': { count: 4, loc: 570 },
  'devices': { count: 4, loc: 147 },
  'firmware-auth': { count: 4, loc: 313 },
  'firmware-updates': { count: 4, loc: 338 },
  'infra': { count: 4, loc: 243 },
  'middleware': { count: 3, loc: 162 },
  'models': { count: 12, loc: 351 },
  'pkg-errors': { count: 1, loc: 62 },
  'pkg-gemini': { count: 1, loc: 89 },
  'pkg-http': { count: 2, loc: 81 },
  'pkg-speech': { count: 1, loc: 104 },
  'pkg-tts': { count: 1, loc: 85 },
  'pkg-utils': { count: 6, loc: 416 },
  'push': { count: 2, loc: 208 },
  'telemetry': { count: 4, loc: 738 },
}

export const UNCLAIMED: string[] = []
