### Activate a registered device
POST http://localhost:8080/api/v1/firmware/devices/activate
Content-Type: application/json
Accept: application/json

{
  "deviceId": "6fdce032-90da-4a27-938b-9b5c367121f4",
  "batteryLevel": 100,
  "firmwareVersion": "1.0.0"
}

### Exchange the device credential for a short-lived token
POST http://localhost:8080/api/v1/firmware/session
Content-Type: application/json
Accept: application/json

{
  "deviceId": "6fdce032-90da-4a27-938b-9b5c367121f4",
  "credential": "EbUwJUa_Me8p3KchOZOH5xWjtVfzIgv_OkR4cdGqBM8"
}
