/**
 * @generated by docs/maps/scripts/architecture-webrtc-sync.mjs — do not edit.
 *
 * Measured from the tree, so the map's numbers cannot drift from the code.
 * `UNCLAIMED` is what no module on the map covers: run the sync script, then
 * either give an existing module a wider pattern in coverage.json or add the
 * node the repo has been missing.
 */

export const MEASURED: Record<string, { count: number; loc: number }> = {
  'camera-handler': { count: 1, loc: 171 },
  'camera-hub': { count: 2, loc: 635 },
  'camera-service': { count: 1, loc: 140 },
  'camera-types': { count: 1, loc: 65 },
  'cane-auth': { count: 1, loc: 45 },
  'command-queue': { count: 5, loc: 675 },
  'jwt-auth': { count: 1, loc: 70 },
  'peer-negotiator': { count: 1, loc: 215 },
  'routes-entry': { count: 2, loc: 177 },
  'sdp-decoder': { count: 2, loc: 480 },
  'session-actor': { count: 1, loc: 193 },
  'shared-pipe': { count: 1, loc: 90 },
}

export const UNCLAIMED: string[] = []
